MangaShop/MangaShop/Controllers/CarrinhoController.cs
using System.Linq;
using MangaShop.Models;
using MangaShop.Repositorio;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Newtonsoft.Json;
using System;
using Serilog;

public class CarrinhoController : Controller
{
    private readonly IProductRepositorio _productRepositorio;
    private readonly IUserRepositorio _userRepositorio;

    public CarrinhoController(IProductRepositorio productRepositorio, IUserRepositorio userRepositorio)
    {
        _productRepositorio = productRepositorio;
        _userRepositorio = userRepositorio;
    }

    public IActionResult Index()
    {

            string userSession = HttpContext.Session.GetString("LoggedUserSession");
            UserModel user = JsonConvert.DeserializeObject<UserModel>(userSession);
            if (user != null)
            {
                var carrinhoItens = _userRepositorio.ObterProdutosDoCarrinho(user.UserId);
                return View(carrinhoItens);
            }

            // Lógica adicional se o usuário não estiver logado
            return RedirectToAction("Login", "Conta"); // Exemplo de redirecionamento para uma página de login
      

    }

    [HttpPost]
    public IActionResult AdicionarAoCarrinho(int productId)
    {
        // Lógica para adicionar um produto ao carrinho
        string userSession = HttpContext.Session.GetString("LoggedUserSession");
        UserModel user = JsonConvert.DeserializeObject<UserModel>(userSession);
        if (user != null)
        {
            // Adicionar lógica para adicionar o produto ao carrinho
            _userRepositorio.AdicionarProdutoAoCarrinho(user.UserId, productId);
        }

        return RedirectToAction("Index");
    }
    [HttpPost]
    public IActionResult RemoverDoCarrinho(int productId)
    {
        // Lógica para remover um produto do carrinho
        string userSession = HttpContext.Session.GetString("LoggedUserSession");
        UserModel user = JsonConvert.DeserializeObject<UserModel>(userSession);
        if (user != null)
        {
            // Adicionar lógica para remover o produto do carrinho
            _userRepositorio.RemoverProdutoDoCarrinho(user.UserId, productId);
        }

        return RedirectToAction("Index");
    }

    private UserModel ObterUsuarioLogado()
    {
        if (HttpContext.Session.TryGetValue("LoggedUserSession", out byte[] userSessionBytes))
        {
            string userSession = System.Text.Encoding.UTF8.GetString(userSessionBytes);
            return JsonConvert.DeserializeObject<UserModel>(userSession);
        }

        return null;
    }
}

MangaShop/MangaShop/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using MangaShop.Models;
using MangaShop.Repositorio;
using Microsoft.AspNetCore.Http;
using Newtonsoft.Json;
using MangaShop.Helper;
using MangaShop.Data;
using Microsoft.AspNetCore.Hosting;
using System.IO;
using System;
using System.Linq;
using Microsoft.EntityFrameworkCore;

namespace MangaShop.Controllers
{
    public class ProductController : Controller
    {
        // Product Repositorio
        private readonly BancoContext _context;
        private readonly IProductRepositorio _productRepositorio;
        private readonly ISessao _sessao;
        private readonly IWebHostEnvironment webHostEnvironment;
        public ProductController(IProductRepositorio ProductRepositorio, ISessao sessao, BancoContext context, IWebHostEnvironment webHost)
        {
            _productRepositorio = ProductRepositorio;
            _sessao = sessao;
            _context = context;
            webHostEnvironment = webHost;
        }
        public IActionResult Index(int id)
        {
            ProductModel product = _productRepositorio.ListByid(id);
            return View("Index", product);
        }

        [HttpPost]
        public IActionResult Pesquisar(string termo)
        {
            if (string.IsNullOrEmpty(termo))
            {
                var todosOsProdutos = _context.Products.ToList();
                return View("ResultadoPesquisa", todosOsProdutos);
            }

            var resultados = _context.Products
                .Where(p => EF.Functions.Like(p.Title, $"%{termo}%"))
                .ToList();

            return View("ResultadoPesquisa", resultados);
        }

        // Criacao do produto
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(ProductModel product)
        {
            string userSession = HttpContext.Session.GetString("LoggedUserSession");
         
            _productRepositorio.Adicionar(product, userSession);
            return View("Index", product);            

        }
        //
        public IActionResult Delete(int id)
        {
            ProductModel product = _productRepositorio.ListByid(id);
            return View(product);
        }
        public IActionResult Deletar(int id)
        {
            _productRepositorio.Deletar(id);
            return RedirectToAction("Index");
        }

        public IActionResult Edit(int id)
        {
            ProductModel product = _productRepositorio.ListByid(id);
            return View(product);
        }
        [HttpPost]
        public IActionResult Edit(ProductModel product)
        {

            _productRepositorio.Editar(product);
            return RedirectToAction("Index");
        }

    }
}

MangaShop/MangaShop/Controllers/UserController.cs
using MangaShop.Helper;
using MangaShop.Models;
using MangaShop.Repositorio;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.IO;
using System.Security.Policy;
using MangaShop.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Routing;

namespace MangaShop.Controllers
{
    public class UserController : Controller
    {

        // User Repositorio
        private readonly BancoContext _context;
        private readonly IUserRepositorio _userRepositorio;
        private readonly IProductRepositorio _productRepositorio;
        private readonly ISessao _sessao;
       
        public UserController(IUserRepositorio userRepositorio, ISessao sessao, BancoContext context, IProductRepositorio productRepositorio)
        {
            _userRepositorio = userRepositorio; 
            _sessao = sessao;
            _context = context;
            _productRepositorio = productRepositorio;
        }
        //

        // Criacao do usuario
        public IActionResult Signup()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Signup(UserModel user)
        {
            if (ModelState.IsValid) {
                _userRepositorio.Adicionar(user);
                return RedirectToAction("Index", "Login");
            }
            
            return View(user);
        }
        //

        // Editar usuario
        public IActionResult Edit(int id)
        {
            UserModel user = _userRepositorio.ListByid(id);
            return View(user);
        }
        [HttpPost]
        public IActionResult Edit(UserModel user)
        {
            
            _userRepositorio.Editar(user);
            _sessao.RemoveUserSession();
            _sessao.CreateUserSession(user);
            return RedirectToAction("Index");
        }
        //
        // Deletar usuario
        public IActionResult Delete(int id)
        {
            UserModel user = _userRepositorio.ListByid(id);
            return View(user);
        }
        public IActionResult Deletar(int id)
        {
            _userRepositorio.Deletar(id);
            return RedirectToAction("Index");
        }
        // Perfil do usuario
        public IActionResult Index(UserModel user)
        {
            return View();
        }
        public IActionResult Conversas(UserModel user)
        {
            return View();
        }

        public IActionResult Carrinho(int id)
        {
            return View();
        }
        [HttpPost]
        public IActionResult UploadIcon(UserModel userModel, IFormFile icon)
        {
            if (icon != null && icon.Length > 0)
            {
                // Verifique se o arquivo foi enviado
                var nomeArquivo = Guid.NewGuid().ToString() + Path.GetExtension(icon.FileName);
                var caminhoDoArquivo = Path.Combine("~/imagens/", nomeArquivo);

                using (var stream = new FileStream(caminhoDoArquivo, FileMode.Create))
                {
                    icon.CopyTo(stream);
                }

       
                userModel.IconPath = nomeArquivo;
            }
            return RedirectToAction("Index");
        }

       


    }
}

MangaShop/MangaShop/Views/User/Carrinho.cshtml
@model UserModel

<head>
    <link rel="stylesheet" href="@Url.Content("~/css/carrinho.css")" />
</head>

@await Component.InvokeAsync("Carrinho")
<div>
    <button onclick="document.getElementById('id01').style.display='block'" id="botao_comprar">Fechar pedido</button>
</div>
<div id="id01" class="modal">
    <span onclick="document.getElementById('id01').style.display='none'" class="close" title="Close Modal">×</span>
    <form class="modal-content" action="/action_page.php">
        <div class="container">
            <h1>Realizar compra</h1>
            <p>Compras em dinheiro devem ser combinadas com o vendedor e não tem suporte da plataforma.</p>

            <div class="clearfix">
                <button type="button" onclick="document.getElementById('id01').style.display='none'" class="pix">Pagamento em PIX</button>
                <a onclick="document.getElementById('id01').style.display='none'" class="dinheiro" href="conversas.html">Pagamento em dinheiro</a>
            </div>
        </div>
    </form>
</div>

MangaShop/MangaShop/Views/User/Conversas.cshtml
@using Microsoft.EntityFrameworkCore.Metadata.Internal;
@model UserModel;
@{
    ViewData["Title"] = "- Conversas";
}



<head>
    <link rel="stylesheet" href="@Url.Content("~/css/chat.css")" />
</head>


<main id="body_main">

    <div id="container">
        <aside>
            <header id="container_header">
                <div id="cabecalho_1">
                    <h1>Conversas</h1>
                    <img src="imagens/config_icone.png" id="config_icone" />
                </div>
                <div id="cabecalho_2"><input type="text" placeholder="Pesquisar" id="pesquisar_conversa"></div>

            </header>
            <ul>
                <li>
                    <button>
                        <img src="imagens/gato_burro.jpg" />
                        <div>
                            <h2>Esmiralhado da Silva</h2>
                            <h3>OK</h3>
                        </div>
                        <span>10:12</span>
                    </button>
                </li>
                <li>
                    <button>
                        <img src="imagens/gato_burro.jpg" />
                        <div>
                            <h2>Esmiralhado da Silva</h2>
                            <h3>OK</h3>
                        </div>
                        <span>10:12</span>
                    </button>
                </li>
                <li>
                    <button>
                        <img src="imagens/gato_burro.jpg" />
                        <div>
                            <h2>Esmiralhado da Silva</h2>
                            <h3>OK</h3>
                        </div>
                        <span>10:12</span>
                    </button>
                </li>
                <li>
                    <button>
                        <img src="imagens/gato_burro.jpg" />
                        <div>
                            <h2>Esmiralhado da Silva</h2>
                            <h3>OK</h3>
                        </div>
                        <span>10:12</span>
                    </button>
                </li>
                <li>
                    <button>
                        <img src="imagens/gato_burro.jpg" />
                        <div>
                            <h2>Esmiralhado da Silva</h2>
                            <h3>OK</h3>
                        </div>
                        <span>10:12</span>
                    </button>
                </li>
                <li>
                    <button>
                        <img src="imagens/gato_burro.jpg" />
                        <div>
                            <h2>Esmiralhado da Silva</h2>
                            <h3>OK</h3>
                        </div>
                        <span>10:12</span>
                    </button>
                </li>
                <li>
                    <button>
                        <img src="imagens/gato_burro.jpg" />
                        <div>
                            <h2>Esmiralhado da Silva</h2>
                            <h3>OK</h3>
                        </div>
                        <span>10:12</span>
                    </button>
                </li>

            </ul>

        </aside>
        <main>
            <header>
                <img src="@Url.Content("~/imagens/gato_burro.jpg")" id="icone_conversa" />
                <div>
                    <h2>Conversa com Esmiralhado da Silva</h2>
                    <h3>Ultima vez online: 10:12</h3>
                </div>
                <button onclick="document.getElementById('id01').style.display='block'" id="botao_denunciar"><img src="imagens/denunciar.png" id="icone_denuncia" /></button>

            </header>
            <ol id="chat">
                <li class="you">
                    <div class="entete">
                        <span class="status green"></span>
                        <h2>Esmiralhado</h2>
                        <h3>10:12, Hoje</h3>
                    </div>
                    <div class="message">
                        LEGAL!
                    </div>
                </li>
                <li class="me">
                    <div class="entete">
                        <h3>10:12, Hoje</h3>
                        <h2>Você</h2>
                        <span class="status blue"></span>
                    </div>
                    <div class="message">
                        OK
                    </div>
                </li>
            </ol>
            <footer id="hud_conversa">

                <textarea rows="10" cols="50" id="txtMsg"></textarea>
                <button type="submit" id="btnSend"><img src="@Url.Content("~/imagens/enviar_icone.png")" /></button>

            </footer>
        </main>
    </div>
    <div id="id01" class="modal">
        <span onclick="document.getElementById('id01').style.display='none'" class="close" title="Close Modal">×</span>
        <form class="modal-content" action="chat.html">
            <div class="container">
                <h1>Denunciar conversa?</h1>
                <p>O histórico de mensagens será enviado para nossos administradores.</p>
                <input type="text" placeholder="Detalhe seu problema." />

                <div class="clearfix">
                    <button type="button" onclick="document.getElementById('id01').style.display='none'" class="denunciar">Denunciar</button>
                    <button type="button" onclick="document.getElementById('id01').style.display='none'" class="cancelar">Cancelar</button>
                </div>
            </div>
        </form>
    </div>
</main>

<script src="~/lib/jquery/dist/jquery.js"></script>
<script src="~/lib/signalr/dist/browser/signalr.js"></script>
<script src="~/js/site.js"></script>

MangaShop/MangaShop/Views/User/Delete.cshtml
@model UserModel
@{
    ViewData["title"] = " - Apagar conta";
}

    <form asp-controller="User" asp-action="Deletar" method="post">
        <h1>Tem certeza que deseja apagar sua conta, @Model.Name?</h1>

        <a asp-route-id="@Model.UserId" asp-controller="User" asp-action="Deletar">Confirmar Exclusão</a>

        <p id="aviso"><a asp-controller="User" asp-action="Index">Cancelar</a></p>

    </form>

MangaShop/MangaShop/Views/User/Edit.cshtml
@model UserModel
@{
    ViewData["Title"] = "- Editar Perfil";
}


<form enctype="multipart/form-data" asp-controller="User" asp-action="Edit" method="post">
    <h1>Registrar-se</h1>

    <input asp-for="Icon" class="custom-file-input" id="FLFrontImage" />


    <label>Nome completo</label><input type="text" asp-for=Name class="barra_texto" />

    <label>E-mail</label><input type="email" asp-for=Email class="barra_texto" />

    <label>CPF</label><input type="text" asp-for=Cpf class="barra_texto" />

    <label>Senha</label><input type="password" asp-for=Password class="barra_texto" />



    <button type="submit">Confirmar</button>
    <p id="aviso"><a asp-controller="User" asp-action="Login">Cancelar</a></p>

</form>

MangaShop/MangaShop/Views/User/Index.cshtml
@model UserModel;
@{
    ViewData["title"] = " - Perfil";
}

<head>
    <link rel="stylesheet" href="~/css/perfil.css" />
</head>

        
    @await Component.InvokeAsync("Information")
    
            <section id="seus_produtos">
                <h1>Seus Produtos</h1>
                    

                    <div id="seus_produtos_corpo">
                        
                        <div id="produtos">
                @await Component.InvokeAsync("Products")
                            
                        </div>

                        <div id="botoes">
                            <a href="" id="laranja_botao">Visualizar todos</a>
                            <a asp-controller="Product" asp-action="Create">Registrar Produtos</a>
                            <a href="">Conversas</a>
                        </div>
                    </div>
            </section>
        </div>

MangaShop/MangaShop/Views/User/Signup.cshtml
@using Microsoft.EntityFrameworkCore.Metadata.Internal;
@model UserModel;
@{
    ViewData["Title"] = "- Registrar-se";
}


<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="@Url.Content("~/css/registro.css")" />
    <title>Manga Shop - Registro</title>
    <script src="todos.js"></script>
</head>


        <form asp-controller="User" asp-action="Signup" method="post">
            <h1>Registrar-se</h1>

            <label>Nome completo</label><input type="text" asp-for=Name class="barra_texto" />
            @Html.ValidationMessageFor(x => x.Name)<br />

            <label>E-mail</label><input type="email" asp-for=Email class="barra_texto" />
            @Html.ValidationMessageFor(x => x.Email)<br />

            <label>CPF</label><input type="text" asp-for=Cpf class="barra_texto" />
            @Html.ValidationMessageFor(x => x.Cpf) <br/>

            <label>Senha</label><input type="password" asp-for=Password class="barra_texto" />
            @Html.ValidationMessageFor(x => x.Password)    <br />

            <button type="submit">Registre-se</button>
            <p id="aviso"><a asp-controller="Login" asp-action="Index">Já tem uma conta? Faça login!</a></p>
        </form>