source/WebAppComercioEletronico/WebAppComercioEletronico/Controllers/LogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebAppComercioEletronico.Controllers
{
    public class LogController : Controller
    {
        // GET: Log
        public ActionResult Index()
        {
            return View();
        }
    }
}

source/WebAppComercioEletronico/WebAppComercioEletronico/Controllers/RegController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebAppComercioEletronico.Controllers
{
    public class RegController : Controller
    {
        // GET: Reg
        public ActionResult Index()
        {
            return View();
        }
    }
}

source/WebAppComercioEletronico/WebAppComercioEletronico/Views/Home/Index.cshtml
@model WebAppComercioEletronico.Models.Home

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Manga Shop - Home</title>
    <link href="~/Content/home.css" rel="stylesheet" />
</head>
<body>

    <header>

        <nav>

            <div id="header_cima">
                <h1 id="logo">
                    <a href="@Url.Action("Index", "Home")"><img src="~/Content/imagens/Logo.png" alt="a logo de uma manga com o nome Manga Shop sobre ela" /></a>
                </h1>

                <form action="pesquisa.html" id="barra_pesquisa">
                    <input type="search" name="pesquisa" placeholder="Pesquise &quot;uma razão para viver&quot;!" />
                    <button type="submit"><img src="~/Content/imagens/lupa.png" /></button>
                </form>

                <ul>
                    <li><a href="@Url.Action("Index", "Reg")">Registrar-se</a></li>
                    <li><a href="@Url.Action("Index", "login")">Entrar</a></li>
                </ul>

            </div>

            <div id="header_baixo">
                <ul>
                    <li><a href="cadastro_produto.html">Vender</a></li>
                    <li><a href="">Suporte</a></li>
                    <li><a href="conversas.html">Conversas</a></li>
                    <li id="lista_desejos"><a href="lista_desejos.html">Lista de Desejos</a></li>
                </ul>
            </div>

        </nav>

    </header>

    <main>

        <div id="banner">
            <img src="~/Content/imagens/banner.png" alt="O melhor site para compra e venda de mangás no Brasil!" />
            <div>O melhor sebo de Mangas dentro do Brasil dentro dos Campus dos IFs pouco nichado graças a deus!</div>
        </div>

        <section id="produtos_recentes">
            <div class="cabecalho">
                <h1>Produtos vistos recentemente</h1>
                <span><a href="">Ver mais</a></span>
            </div>

            <div id="vistos_recentemente">
                <a href=""><div class="produto_1"><img src="~/Content/imagens/manga_berserk.png" /></div></a>
                <a href=""><div class="produto_2"><img src="~/Content/imagens/manga_kimetsu.png" /></div></a>
                <a href=""><div class="produto_3"><img src="~/Content/imagens/hq_anoum.png" /></div></a>
                <a href=""><div class="produto_4"><img src="~/Content/imagens/hq_missionario.png" /></div> </a>
            </div>
        </section>

        <section id="vendedores">
            <div class="cabecalho">
                <h1>Vendedores na área</h1>
            </div>

            <a href="@Url.Action("Index", "Perfil")">
                <div class="informacoes_vendedor">
                    <div class="imagem_perfil">
                        <svg height="74" width="74">
                            <defs>
                                <clipPath id="icone_perfil">
                                    <circle cx="37" cy="37" r="35" stroke="black" stroke-width="3" fill="none" />
                                </clipPath>
                            </defs>
                            <image width="80" height="80" xlink:href="~/Content/imagens/gato_burro.jpg" clip-path="url(#icone_perfil) " />
                        </svg>
                    </div>
                    <div class="vendedor_dados">
                        <h3>Esfarrapo da Silva Difunto</h3>
                        <p>Campus Natal Central</p>
                    </div>
                </div>
            </a>

            <a href="@Url.Action("Index", "Perfil")">
                <div class="informacoes_vendedor">
                    <div class="imagem_perfil">
                        <svg height="74" width="74">
                            <defs>
                                <clipPath id="icone_perfil">
                                    <circle cx="37" cy="37" r="35" stroke="black" stroke-width="3" fill="none" />
                                </clipPath>
                            </defs>
                            <image width="80" height="80" xlink:href="~/Content/imagens/gato_burro.jpg" clip-path="url(#icone_perfil)" />
                        </svg>
                    </div>
                    <div class="vendedor_dados">
                        <h3>Esfarrapo da Silva Difunto</h3>
                        <p>Campus Natal Central</p>
                    </div>
                </div>
            </a>

            <a href="@Url.Action("Index", "Perfil")">
                <div class="informacoes_vendedor">
                    <div class="imagem_perfil">
                        <svg height="74" width="74">
                            <defs>
                                <clipPath id="icone_perfil">
                                    <circle cx="37" cy="37" r="35" stroke="black" stroke-width="3" fill="none" />
                                </clipPath>
                            </defs>
                            <image width="80" height="80" xlink:href="~/Content/imagens/gato_burro.jpg" clip-path="url(#icone_perfil)" />
                        </svg>
                    </div>
                    <div class="vendedor_dados">
                        <h3>Esfarrapo da Silva Difunto</h3>
                        <p>Campus Natal Central</p>
                    </div>
                </div>
            </a>

            <a href="@Url.Action("Index", "Perfil")">
                <div class="informacoes_vendedor">
                    <div class="imagem_perfil">
                        <svg height="74" width="74">
                            <defs>
                                <clipPath id="icone_perfil">
                                    <circle cx="37" cy="37" r="35" stroke="black" stroke-width="3" fill="none" />
                                </clipPath>
                            </defs>
                            <image width="80" height="80" xlink:href="~/Content/imagens/gato_burro.jpg" clip-path="url(#icone_perfil)" />
                        </svg>
                    </div>
                    <div class="vendedor_dados">
                        <h3>Esfarrapo da Silva Difunto</h3>
                        <p>Campus Natal Central</p>
                    </div>
                </div>
            </a>

            <button class="ver_mais">Ver mais</button>

        </section>

        <section id="seus_produtos">
            <div class="cabecalho">
                <h2>Seus produtos</h2>
                <span><a href="">Ver mais</a></span>
            </div>

            <div id="produtos_seus">
                <a href=""><div class="produto_1"><img src="~/Content/imagens/manga_berserk.png" /></div></a>
                <a href=""><div class="produto_2"><img src="~/Content/imagens/manga_kimetsu.png" /></div></a>
                <a href=""><div class="produto_3"><img src="~/Content/imagens/hq_anoum.png" /></div></a>
                <a href=""><div class="produto_4"><img src="~/Content/imagens/hq_missionario.png" /></div> </a>
            </div>
        </section>

        <section id="recomendados">
            <h1>Recomendados para você</h1>

            <div id="produtos">
                <div class="produto">
                    <a href="">
                        <div class="imagem_produto">
                            <img src="~/Content/imagens/mangas.png" />
                        </div>
                        <div class="detalhes_produto">
                            <h3>Coleção de mangás</h3>
                            <p>R$ 80000,21</p>
                            <h4><a href="">Esfarrapo da Silva</a> - Natal Central</h4>
                        </div>
                    </a>
                </div>

                <div class="produto">
                    <a href="">
                        <div class="imagem_produto">
                            <img src="~/Content/imagens/mangas.png" />
                        </div>
                        <div class="detalhes_produto">
                            <h3>Coleção de mangás</h3>
                            <p>R$ 80000,21</p>
                            <h4><a href="">Esfarrapo da Silva</a> - Natal Central</h4>
                        </div>
                    </a>
                </div>

                <div class="produto">
                    <a href="">
                        <div class="imagem_produto">
                            <img src="~/Content/imagens/mangas.png" />
                        </div>
                        <div class="detalhes_produto">
                            <h3>Coleção de mangás</h3>
                            <p>R$ 80000,21</p>
                            <h4><a href="">Esfarrapo da Silva</a> - Natal Central</h4>
                        </div>
                    </a>
                </div>

                <div class="produto">
                    <a href="">
                        <div class="imagem_produto">
                            <img src="~/Content/imagens/mangas.png" />
                        </div>
                        <div class="detalhes_produto">
                            <h3>Coleção de mangás</h3>
                            <p>R$ 80000,21</p>
                            <h4><a href="">Esfarrapo da Silva</a> - Natal Central</h4>
                        </div>
                    </a>
                </div>

                <div class="produto">
                    <a href="">
                        <div class="imagem_produto">
                            <img src="~/Content/imagens/mangas.png" />
                        </div>
                        <div class="detalhes_produto">
                            <h3>Coleção de mangás</h3>
                            <p>R$ 80000,21</p>
                            <h4><a href="">Esfarrapo da Silva</a> - Natal Central</h4>
                        </div>
                    </a>
                </div>

                <div class="produto">
                    <a href="">
                        <div class="imagem_produto">
                            <img src="~/Content/imagens/mangas.png" />
                        </div>
                        <div class="detalhes_produto">
                            <h3>Coleção de mangás</h3>
                            <p>R$ 80000,21</p>
                            <h4><a href="">Esfarrapo da Silva</a> - Natal Central</h4>
                        </div>
                    </a>
                </div>

                <div class="produto">
                    <a href="">
                        <div class="imagem_produto">
                            <img src="~/Content/imagens/mangas.png" />
                        </div>
                        <div class="detalhes_produto">
                            <h3>Coleção de mangás</h3>
                            <p>R$ 80000,21</p>
                            <h4><a href="">Esfarrapo da Silva</a> - Natal Central</h4>
                        </div>
                    </a>
                </div>

                <div class="produto">
                    <a href="">
                        <div class="imagem_produto">
                            <img src="~/Content/imagens/mangas.png" />
                        </div>
                        <div class="detalhes_produto">
                            <h3>Coleção de mangás</h3>
                            <p>R$ 80000,21</p>
                            <h4><a href="">Esfarrapo da Silva</a> - Natal Central</h4>
                        </div>
                    </a>
                </div>
            </div>

            <button class="ver_mais">Ver mais</button>
        </section>

    </main>

    <footer>

        <address>
            <div id="contatos">
                <p>Contato para suporte: mangashop@suporte.com</p>
                <p>Contato profissional: mangashop@contato.com</p>
            </div>

            <div id="contatos_2">
                <p>CNPJ n.º 00.000.000/0000-00 / Av. Num sei o que num sei o que lá nº 8, Ohio, Natal/RN - CEP 00000-000 - empresa do grupo Manga Shop.</p>
                <p>Copyright © 1799-2023 dorpura.com.br LTDA.</p>
            </div>
        </address>

    </footer>
</body>
</html>

source/WebAppComercioEletronico/WebAppComercioEletronico/Views/Login/login.cshtml
@model WebAppComercioEletronico.Models.Usuario

@{
    ViewBag.Title = "Login";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<head>
    <title>Manga Shop - Login</title>
    <link href="~/Content/login.css" rel="stylesheet" />
</head>

<body>

    <form action="@Url.Action("perfil", "Perfil")">

        <h1>Login</h1>
    
        <label>E-mail<input class="barra_texto" type="email" placeholder="shaolinmatadordeporco02@email.com" required /></label>
    
        <label>Senha<input class="barra_texto" type="password" placeholder="*******" required /></label>
    
        <div id="avisos">
            <p><a href="">Esqueci minha senha</a></p>
            <p><a href="@Url.Action("registro", "Registro")">Não tem uma conta? Registre-se!</a></p>
        </div>
    
        <button type="submit" id="entrar">Entrar</button>
    </form>

</body>

source/WebAppComercioEletronico/WebAppComercioEletronico/Views/Perfil/perfil.cshtml
@model WebAppComercioEletronico.Models.Usuario

@{
    ViewBag.Title = "Perfil";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<head>
    <title>Manga Shop - Perfil</title>
    <link href="~/Content/Perfil.css" rel="stylesheet" />
</head>

<body>

    <div id="icone">
        <button> 
            <svg height="110" width="110">
                <defs>
                    <clipPath id="icone_perfil">
                        <circle cx="50" cy="50" r="50" stroke="black" stroke-width="3" fill="none" />
                    </clipPath>
                </defs>
                <image width="100" height="100" xlink:href="~/Content/imagens/gato_burro.jpg" clip-path="url(#icone_perfil)" />
            </svg>
        </button>
    </div>

    <div id="nao_icone">
        <section id="informacoes_perfil">

            <div class="cabecalho">
                <h1> Dados Pessoais</h1>
                <a class="botoes_fofos" href="">Editar perfil</a>
            </div>

            <table class="dados">
                <tr>
                    <th>Nome Completo:</th>
                    <th>Esfarrapo da Silva Júnior</th> <!-- Banco de dados-->
                </tr>
                <tr>
                    <th>Celular:</th>
                    <th>+55 (84) 0000-0000</th> <!-- Banco de dados-->
                </tr>
                <tr>
                    <th>CPF:</th>
                    <th>000.000.000-00</th> <!-- Banco de dados-->
                </tr>
                <tr>
                    <th>Campus:</th>
                    <th>Natal Central</th> <!-- Banco de dados-->
                </tr>
                <tr>
                    <th>Curso:</th>
                    <th>Infoweb</th> <!-- Banco de dados-->
                </tr>
            </table>
        </section>

        <section id="seguranca">
            <h1>Segurança</h1>
                <table class="dados">
                    <tr>
                        <th>E-mail:</th>
                        <th>rafael.cunha@escolar.ifrn.ed.br</th> <!-- Banco de dados-->
                    </tr>
                    <tr>
                        <th>Senha:</th>
                        <th>********</th> <!-- Banco de dados-->
                    </tr>
                </table>
                <div id="botoes_seguranca">
                    <a class="botoes_fofos" href="">Alterar Senha</a>
                    <a class="botoes_fofos" href="">Alterar E-mail</a>
                </div>
        </section>

        <section id="seus_produtos">
            <h1>Seus Produtos</h1>
                <div id="seus_produtos_corpo">
                    <div id="produtos">
                        <div class="produto">
                            <a href="">
                                <div class="imagem_produto">
                                    <img src="~/Content/imagens/mangas.png" />
                                </div>
                                <div class="detalhes_produto">
                                    <h3>Coleção de mangás</h3>
                                    <p>R$ 80000,21</p>
                                </div>
                            </a>
                        </div>

                        <div class="produto">
                            <a href="">
                                <div class="imagem_produto">
                                    <img src="~/Content/imagens/mangas.png" />
                                </div>
                                <div class="detalhes_produto">
                                    <h3>Coleção de mangás</h3>
                                    <p>R$ 80000,21</p>
                                </div>
                            </a>
                        </div>

                        <div class="produto">
                            <a href="">
                                <div class="imagem_produto">
                                    <img src="~/Content/imagens/mangas.png" />
                                </div>
                                <div class="detalhes_produto">
                                    <h3>Coleção de mangás</h3>
                                    <p>R$ 80000,21</p>
                                </div>
                            </a>
                        </div>
                    </div>

                    <div id="botoes">
                        <a href="" style="background-color: #f28a3c;">Visualizar todos</a>
                        <a href="">Registrar Produtos</a>
                        <a href="">Conversas</a>
                    </div>
                </div>
        </section>
    </div>

</body>