MangaShop/MangaShop/Controllers/CarrinhoController.cs
using System.Linq;
using MangaShop.Models;
using MangaShop.Repositorio;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using Newtonsoft.Json;
using System;
using Serilog;

public class CarrinhoController : Controller
{
    private readonly IProductRepositorio _productRepositorio;
    private readonly IUserRepositorio _userRepositorio;

    public CarrinhoController(IProductRepositorio productRepositorio, IUserRepositorio userRepositorio)
    {
        _productRepositorio = productRepositorio;
        _userRepositorio = userRepositorio;
    }

    public IActionResult Index()
    {

            string userSession = HttpContext.Session.GetString("LoggedUserSession");
            UserModel user = JsonConvert.DeserializeObject<UserModel>(userSession);
            if (user != null)
            {
                var carrinhoItens = _userRepositorio.ObterProdutosDoCarrinho(user.UserId);
                return View(carrinhoItens);
            }

            // Lógica adicional se o usuário não estiver logado
            return RedirectToAction("Login", "Conta"); // Exemplo de redirecionamento para uma página de login
      

    }

    [HttpPost]
    public IActionResult AdicionarAoCarrinho(int productId)
    {
        // Lógica para adicionar um produto ao carrinho
        string userSession = HttpContext.Session.GetString("LoggedUserSession");
        UserModel user = JsonConvert.DeserializeObject<UserModel>(userSession);
        if (user != null)
        {
            // Adicionar lógica para adicionar o produto ao carrinho
            _userRepositorio.AdicionarProdutoAoCarrinho(user.UserId, productId);
        }

        return RedirectToAction("Index");
    }
    [HttpPost]
    public IActionResult RemoverDoCarrinho(int productId)
    {
        // Lógica para remover um produto do carrinho
        string userSession = HttpContext.Session.GetString("LoggedUserSession");
        UserModel user = JsonConvert.DeserializeObject<UserModel>(userSession);
        if (user != null)
        {
            // Adicionar lógica para remover o produto do carrinho
            _userRepositorio.RemoverProdutoDoCarrinho(user.UserId, productId);
        }

        return RedirectToAction("Index");
    }

    private UserModel ObterUsuarioLogado()
    {
        if (HttpContext.Session.TryGetValue("LoggedUserSession", out byte[] userSessionBytes))
        {
            string userSession = System.Text.Encoding.UTF8.GetString(userSessionBytes);
            return JsonConvert.DeserializeObject<UserModel>(userSession);
        }

        return null;
    }
}

MangaShop/MangaShop/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using MangaShop.Models;
using MangaShop.Repositorio;
using Microsoft.AspNetCore.Http;
using Newtonsoft.Json;
using MangaShop.Helper;
using MangaShop.Data;
using Microsoft.AspNetCore.Hosting;
using System.IO;
using System;
using System.Linq;
using Microsoft.EntityFrameworkCore;

namespace MangaShop.Controllers
{
    public class ProductController : Controller
    {
        // Product Repositorio
        private readonly BancoContext _context;
        private readonly IProductRepositorio _productRepositorio;
        private readonly ISessao _sessao;
        private readonly IWebHostEnvironment webHostEnvironment;
        public ProductController(IProductRepositorio ProductRepositorio, ISessao sessao, BancoContext context, IWebHostEnvironment webHost)
        {
            _productRepositorio = ProductRepositorio;
            _sessao = sessao;
            _context = context;
            webHostEnvironment = webHost;
        }
        public IActionResult Index(int id)
        {
            ProductModel product = _productRepositorio.ListByid(id);
            return View("Index", product);
        }

        [HttpPost]
        public IActionResult Pesquisar(string termo)
        {
            if (string.IsNullOrEmpty(termo))
            {
                var todosOsProdutos = _context.Products.ToList();
                return View("ResultadoPesquisa", todosOsProdutos);
            }

            var resultados = _context.Products
                .Where(p => EF.Functions.Like(p.Title, $"%{termo}%"))
                .ToList();

            return View("ResultadoPesquisa", resultados);
        }

        // Criacao do produto
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(ProductModel product)
        {
            string userSession = HttpContext.Session.GetString("LoggedUserSession");
         
            _productRepositorio.Adicionar(product, userSession);
            return View("Index", product);            

        }
        //
        public IActionResult Delete(int id)
        {
            ProductModel product = _productRepositorio.ListByid(id);
            return View(product);
        }
        public IActionResult Deletar(int id)
        {
            _productRepositorio.Deletar(id);
            return RedirectToAction("Index");
        }

        public IActionResult Edit(int id)
        {
            ProductModel product = _productRepositorio.ListByid(id);
            return View(product);
        }
        [HttpPost]
        public IActionResult Edit(ProductModel product)
        {

            _productRepositorio.Editar(product);
            return RedirectToAction("Index");
        }

    }
}

MangaShop/MangaShop/Views/Product/Create.cshtml
@using Microsoft.EntityFrameworkCore.Metadata.Internal;
@model ProductModel;
@{
    ViewData["Title"] = "- Vender";
}


<head>
    <link rel="stylesheet" href="~/css/criar_produto.css" />
</head>


<form asp-controller="Product" asp-action="Create" method="post" enctype="multipart/form-data">
 
        <input asp-for="Image" class="custom-file-input" id="FLFrontImage" />

    <div id="registro_produto">

        <label>Nome do produto</label><input class="barra_texto" type="text" asp-for=Title>
        
        <label>Descrição do produto</label><input class="barra_texto_2" type="text" asp-for=Description>
        
        <label>Condição do produto</label>
            <select id="condicao_produto" asp-for=Conservacao>
                <option value="lacrado">Lacrado</option>
                <option value="novo">Novo</option>
                <option value="seminovo">Seminovo</option>
                <option value="gasto">Gasto</option>
                <option value="danificado">Danificado</option>
            </select>
        
        <label id="preco_produto">Preço</label><input type="number" asp-for=Value/>
        
       
    </div>
    <button type="submit" id="submeter_produto">Pronto </button>
</form>

MangaShop/MangaShop/Views/Product/Edit.cshtml
@using Microsoft.EntityFrameworkCore.Metadata.Internal;
@model ProductModel;
@{
    ViewData["Title"] = "- Editar";
}


<head>
    <link rel="stylesheet" href="~/css/criar_produto.css" />
</head>


<form  asp-controller="Product" asp-action="Edit" method="post" enctype="multipart/form-data">
    <fieldset id="imagens_produto">
        <input asp-for="Image" class="custom-file-input" id="FLFrontImage" />
    </fieldset>
    <fieldset id="registro_produto">


        <label>Nome do produto</label><input class="barra_texto" type="text" asp-for=Title>

        <label>Descrição do produto</label><input class="barra_texto_2" type="text" asp-for=Description>

        <label>Condição do produto</label>
        <select id="condicao_produto" asp-for=Conservacao>
            <option value="lacrado">Lacrado</option>
            <option value="novo">Novo</option>
            <option value="seminovo">Seminovo</option>
            <option value="gasto">Gasto</option>
            <option value="danificado">Danificado</option>
        </select>

        <label id="preco_produto">Preço</label><input type="number" asp-for=Value />

    </fieldset>
    <button type="submit" id="submeter_produto">Pronto </button>
</form>

MangaShop/MangaShop/Views/Product/Index.cshtml
@model ProductModel;


<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="@Url.Content("~/css/produto.css")" />
    <script src="~/js/todos.js"></script>
</head>



<section id="imagens_produto">

    <div id="produto_selecionado">
        <button onclick=""><img id="produtinho_selecionado" onclick="" src="~/imagens/@Model.ImagePath" /></button>
    </div>

</section>

<section id="informacoes_produto">

    <div class="informacoes">
        <h1 id="nome_produto">@Model.Title</h1>
        <h3 id="nome_vendedor"><a href="">@Model.UserId</a> - Campus <span id="campus">@Model</span></h3>
    </div>
    <div class="informacoes" id="produto_informacoes">
        <div>
            <h2 id="preco_produto">R$ @Model.Value</h2>
            <h3 id="forma_pagamento">Apenas dinheiro e PIX</h3>
        </div>
        <div>
            <input type="checkbox" class="checkbox" id="checkbox" checked />
            <label for="checkbox">
                <svg id="heart-svg" viewBox="467 392 58 57" xmlns="http://www.w3.org/2000/svg">
                    <g id="Group" fill="none" fill-rule="evenodd" transform="translate(467 392)">
                        <path id="heart" d="M29.144 20.773c-.063-.13-4.227-8.67-11.44-2.59C7.63 28.795 28.94 43.256 29.143 43.394c.204-.138 21.513-14.6 11.44-25.213-7.214-6.08-11.377 2.46-11.44 2.59z" fill="#eeeeee" />
                        <circle id="main-circ" fill="#E2264D" opacity="0" cx="29.5" cy="29.5" r="1.5" />

                        <g id="grp7" opacity="0" transform="translate(7 6)">
                            <circle id="oval1" fill="#9CD8C3" cx="2" cy="6" r="2" />
                            <circle id="oval2" fill="#8CE8C3" cx="5" cy="2" r="2" />
                        </g>

                        <g id="grp6" opacity="0" transform="translate(0 28)">
                            <circle id="oval1" fill="#CC8EF5" cx="2" cy="7" r="2" />
                            <circle id="oval2" fill="#91D2FA" cx="3" cy="2" r="2" />
                        </g>

                        <g id="grp3" opacity="0" transform="translate(52 28)">
                            <circle id="oval2" fill="#9CD8C3" cx="2" cy="7" r="2" />
                            <circle id="oval1" fill="#8CE8C3" cx="4" cy="2" r="2" />
                        </g>

                        <g id="grp2" opacity="0" transform="translate(44 6)">
                            <circle id="oval2" fill="#CC8EF5" cx="5" cy="6" r="2" />
                            <circle id="oval1" fill="#CC8EF5" cx="2" cy="2" r="2" />
                        </g>

                        <g id="grp5" opacity="0" transform="translate(14 50)">
                            <circle id="oval1" fill="#91D2FA" cx="6" cy="5" r="2" />
                            <circle id="oval2" fill="#91D2FA" cx="2" cy="2" r="2" />
                        </g>

                        <g id="grp4" opacity="0" transform="translate(35 50)">
                            <circle id="oval1" fill="#F48EA7" cx="6" cy="5" r="2" />
                            <circle id="oval2" fill="#F48EA7" cx="2" cy="2" r="2" />
                        </g>

                        <g id="grp1" opacity="0" transform="translate(24)">
                            <circle id="oval1" fill="#9FC7FA" cx="2.5" cy="3" r="2" />
                            <circle id="oval2" fill="#9FC7FA" cx="7.5" cy="2" r="2" />
                        </g>
                    </g>
                </svg>
            </label>
        </div>
    </div>
    
    
    <form asp-controller="Carrinho" asp-action="AdicionarAoCarrinho" method="post">
        <input type="hidden" name="productId" value="@Model.ProductId" />
        <button type="submit">Adicionar ao Carrinho</button>
    </form>
    <div id="id01" class="modal">
        <span onclick="document.getElementById('id01').style.display='none'" class="close" title="Close Modal">×</span>
        <form class="modal-content" action="/action_page.php">
            <div class="container">
                <h1>Realizar compra</h1>
                <p>Compras em dinheiro devem ser combinadas com o vendedor e não tem suporte da plataforma.</p>

                <div class="clearfix">
                    <a href="chat_comprar.html" class="pix">
                        Pagamento em PIX</button>
                        <a onclick="document.getElementById('id01').style.display='none'" class="dinheiro" href="chat.html">Pagamento em dinheiro</a>
                </div>
            </div>
        </form>
    </div>

</section>

<section id="descricao_produto">
    <p>
        @Model.Description
    </p>

</section>

MangaShop/MangaShop/Views/Product/ResultadoPesquisa.cshtml
@model List<ProductModel>

<head>
    <link rel="stylesheet" href="~/css/pesquisar_produto.css" />
</head>

<section id="resultado">

    @if(Model != null && Model.Count != 0)
    {
         <h1>Resultados da pesquisa:</h1>
         <div id="produtos">
            @foreach (var produto in Model)
            {
                 <div class="produto">
                     <a href="@Url.Action("Index", "Product", new { id = produto.Id })">
                         <div class="imagem_produto">
                             <img src="~/imagens/@produto.ImagePath" />
                         </div>
                         <div class="detalhes_produto">
                             <h3>@produto.Title</h3>
                             <p>@String.Format("R$ {0:N2}", produto.Value)</p>
                         </div>
                     </a>
                 </div>
            }
         </div>  

     }
     else
     {
         <h2>Nenhum resultado para sua pesquisa</h2>
     }

</section>